version: '3.8'

services:
  deepgemini:
    image: bradleylzh/deepgemini:latest
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./deepgemini.db:/app/deepgemini.db
    restart: unless-stopped 